### ISSUE TITLE
CSI plugin killed due to OOM

### ISSUE THREAD

**Issue by scarlet-storm** [LightBitsLabs/los-csi#33]
Recently after a maintenance activity where we have restarted kubelet, we observed that the CSI plugin is getting oom killed. From the logs, this seems to happen when volume access mode is BLOCK and NodePublishVolume rpc is called on already published volume. (LBS-392). When kubelet is restarted with running pods, it seems to call NodePublishVolume on all PVC as part of syncing it's internal state. This issue is not reproducible in normal circumstances as the volumes are published/unpublished whenver the pod is created and deleted.
The CSI spec requires that NodePublishVolume is idempotent
> This operation MUST be idempotent. If the volume corresponding to the volume_id has already been published at the specified target_path, and is compatible with the specified volume_capability and readonly flag, the Plugin MUST reply 0 OK.

>If this RPC failed, or the CO does not know if it failed or not, it MAY choose to call NodePublishVolume again, or choose to call NodeUnpublishVolume.

Using pprof, we found that most of the memory allocations had following stack trace.
```
heap profile: 27: 4377587200 [72: 21883025216] @ heap/1048576
1: 4377370624 [1: 4377370624] @ 0x4e1c45 0x900bac 0x900ba7 0x907485 0x90747a 0x99dbe5 0x99ef68 0x8b9078 0x8f25d3 0x8d067a 0x92d6a2 0x8d067a 0x8f2f42 0x8d067a 0x8d0f66 0x8d067a 0x8d051e 0x8b8f38 0x89038b 0x89486f 0x88de78 0x46c8a1
#       0x4e1c44        os.ReadFile+0x1a4                                                                                       os/file.go:722
#       0x900bab        io/ioutil.ReadFile+0x4b                                                                                 io/ioutil/ioutil.go:37
#       0x900ba6        k8s.io/utils/io.consistentReadSync+0x46                                                                 k8s.io/utils@v0.0.0-20210707171843-4b05e18ac7d9/io/read.go:44
#       0x907484        k8s.io/utils/io.ConsistentRead+0x24                                                                     k8s.io/utils@v0.0.0-20210707171843-4b05e18ac7d9/io/read.go:37
#       0x907479        k8s.io/mount-utils.ListProcMounts+0x19                                                                  k8s.io/mount-utils@v0.21.4/mount_linux.go:503
#       0x99dbe4        github.com/lightbitslabs/los-csi/pkg/driver.getDeviceNameFromMount+0x44                                 github.com/lightbitslabs/los-csi/pkg/driver/node.go:525
#       0x99ef67        github.com/lightbitslabs/los-csi/pkg/driver.(*Driver).NodePublishVolume+0xb27                           github.com/lightbitslabs/los-csi/pkg/driver/node.go:631
#       0x8b9077        github.com/container-storage-interface/spec/lib/go/csi._Node_NodePublishVolume_Handler.func1+0x77       github.com/container-storage-interface/spec@v1.3.0/lib/go/csi/csi.pb.go:5977
```
Investigating the code, we found the following
https://github.com/LightBitsLabs/los-csi/blob/284beba62e55e13404b81ff0cefe57f4765b7f9c/pkg/driver/node.go#L624-L631

In case the target_path is not already a mountpoint, the block device is bind mounted to the target_path and success is returned. But if it's already a mountpoint (in the case of second NodePublishVolume call), getDeviceNameFromMount is called.

https://github.com/LightBitsLabs/los-csi/blob/284beba62e55e13404b81ff0cefe57f4765b7f9c/pkg/driver/node.go#L524-L525

GetDeviceNameFromMount calls ListProcMounts from k8s mount-utils with the target_path (Path where block device is already bind mounted) . ListProcMounts expects the path to the file containing list of mounts (/proc/mounts). This can be seen for example from following code
https://github.com/kubernetes/mount-utils/blob/2169101294f01f6b20ee913f246a83d3b2829fd1/mount_linux.go#L385
https://github.com/kubernetes/mount-utils/blob/2169101294f01f6b20ee913f246a83d3b2829fd1/mount_linux.go#L45
Calling the function with the path to the block device, causes the entire block device to be read into memory, which causes the oom kill. Heavy disk read activity is also seen during the same time, indicating the same.
```

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.08    0.00    0.45    0.56    0.00   98.92

Device            r/s     rkB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wkB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dkB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
nvme7c7n1     11611.00 743056.00     0.00   0.00    0.25    64.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    2.86  93.60


avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.00    0.44    0.59    0.00   98.97

Device            r/s     rkB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wkB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dkB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
nvme7c7n1     12813.00 820080.00     0.00   0.00    0.24    64.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    3.07 100.00


avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.59    0.00    0.33    0.38    0.00   98.70

Device            r/s     rkB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wkB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dkB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
nvme7c7n1     8165.00 522512.00     0.00   0.00    0.24    63.99    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    1.95  65.20
```

**Comment by muliby-lb** [comment]
Thank you @scarlet-storm, that's a great bug report. @yogev-lb is investigating and working on a fix.
